version: '3.1'
services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports: 
      - "8080:80"
  
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports: 
      - "80:80"
    depends_on:
      - frontend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports: 
      - "5000:5000"